JobtransparencyNLP/users/views.py
import os
from flask import Blueprint,render_template, redirect, url_for,flash, request
from flask_login import login_user,login_required,logout_user,current_user
from JobtransparencyNLP import db
from JobtransparencyNLP.models import User, UserRole
from JobtransparencyNLP.users.forms import RemoveRoles,RegistrationForm,LoginForm,AssignRoles

users_blueprint = Blueprint('users',__name__, template_folder='templates/users')
def getUsers():
    UserChoices = []
    for Cuser in User.query.all():
        UserChoices.append((Cuser.id,Cuser.email))
    
    return UserChoices

def getRoles():
    UserRoles = []
    for roles in UserRole.query.all():
        UserRoles.append((roles.id,roles.rolename))
    
    return UserRoles
@users_blueprint.route('/logout')
def logout():
    logout_user()
    flash('You Logged out')
    return redirect(url_for('index'))

@users_blueprint.route('/removeroles', methods=['GET','POST'])
@login_required
def removeroles():
    form = RemoveRoles()
    form.Roles.choices = getRoles()
    form.Users.choices = getUsers()
    for role in current_user.roles:
        if role.rolename == 'SuperUser':
            if form.is_submitted():
                curUser = User.query.filter_by(id=form.Users.data).first()
                Role = UserRole.query.filter_by(id=form.Roles.data).first()
                if Role in curUser.roles:
                    curUser.roles.remove(Role)

                db.session.commit()
                return redirect(url_for('index'))
                
    return render_template('assignroles.html',form=form)

@users_blueprint.route('/assignroles', methods=['GET','POST'])
@login_required
def assignroles():
    form = AssignRoles()
    form.Roles.choices = getRoles()
    form.Users.choices = getUsers()
    for role in current_user.roles:
        if role.rolename == 'SuperUser':

            if form.validate_on_submit():
                curUser = User.query.filter_by(email=form.Users.data).first()
                adminRole = UserRole.query.filter_by(rolename=form.Roles.data).first()
                curUser.roles.append(curUser)
                db.session.commit()
                return redirect(url_for('index'))

            
            return render_template('assignroles.html',form=form)

    flash('You do not have the role to view this page')
    return redirect(url_for('index'))

@users_blueprint.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in')
            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('index')

            return redirect(next)

    return render_template('login.html',form=form)

@users_blueprint.route('/register', methods=['GET','POST'])
def register():

    form = RegistrationForm()
   
    if form.validate_on_submit():
        user = User(email = form.email.data,
                    username=form.username.data, 
                    password=form.password.data)

        if UserRole.query.count() == 0:
            adminRole = UserRole(rolename='Admin')
            superRole = UserRole(rolename='SuperUser')
            db.session.add(adminRole)
            db.session.add(superRole)
            db.session.commit()
        
        adminRole = UserRole.query.filter_by(rolename='Admin').first()
        superRole = UserRole.query.filter_by(rolename='SuperUser').first()

        if form.adminkey.data == os.environ['SECRET_KEY']: #SECRET_KEY:
            user.roles.append(adminRole)

        if form.adminkey.data == os.environ['SECRET_KEY']: #SECRET_KEY+"Super":
            user.roles.append(superRole)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registering')
        return redirect(url_for('users.login'))


    return render_template('register.html',form=form)

JobtransparencyNLP/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/minty/bootstrap.min.css"
    integrity="sha384-H4X+4tKc7b8s4GoMrylmy2ssQYpDHoqzPa9aKXbDwPoPUA3Ra8PA5dGzijN+ePnH" crossorigin="anonymous">
  <title>NLP</title>
</head>

<body>
  {% with messages = get_flashed_messages() %} {% if messages %} {% for
    message in messages %}
  <div class="alert alert-primary" role="alert">{{ message }}</div>
  {% endfor %} {% endif %} {% endwith %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav mr-auto">
      <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
       {% if current_user.is_authenticated %}
          <a class="nav-item nav-link">Hi {{ current_user.username }}!</a>
       {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}

        {% for role in current_user.roles %}
          {% if role.rolename == 'SuperUser'%}
            <a class="nav-item nav-link" href="{{ url_for('users.assignroles') }}">Assign Roles</a>
            <a class="nav-item nav-link" href="{{ url_for('users.removeroles') }}">Remove Roles</a>
          {% endif %}
        {% endfor %} 
        
        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">logout</a>
        
      {% else %}

        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>

        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
      {% endif %}
    </ul>
  </nav>
  <div class="container">
    {% block content %} {% endblock %}
  </div>
</body>
<footer>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <script defer src="https://www.avaanalytics.com/js/prod/count.min.js"
    data-sharpcounter="https://www.avaanalytics.com/api/Interaction/Count"
    data-sharpcounter-apikey="eeee080c-ba52-4652-93f6-12c28597e6f8"></script>
</footer>

</html>

JobtransparencyNLP/templates/home.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron text-center">
  <h1>Welcome to Text Classify</h1>
  <p>Serving your NLP Needs</p>
</div>
<div class="jumbotron text-center">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3>Regsiter to Use</h3>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 text-center">
      <h4>Summaries End Point</h4>
      <h6>Base URI /stats/extract_summary_from_text</h6>
    </div>
    <div class="col-sm-6 text-center">
      <h4>Key Phrases End Point</h4>
      <h6>Base URI /stats/extract_keyphrases_from_text</h6>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 text-center">
      <h4>Summaries Extracted To Date</h4>
      <h6><b>{{homepage["stats_summary"].hit_count}}</b></h6>
    </div>
    <div class="col-sm-6 text-center">
      <h4>Key Phrases Extracted To Date</h4>
      <h6><b>{{homepage["stats_keyphrases"].hit_count}}</b></h6>
    </div>
  </div>
</div>
<div style="padding-top:20px;"></div>
<div class="container">
 <div class="row">
    <table class="table text-center">
      <thead>
        <tr>
          <th class="text-center" scope="col">Last X Days</th>
          <th class="text-center" scope="col">Requests Processed</th>
        </tr>
      </thead>
      <tbody>
      {% for results in homepage["history"] %}
        <tr>
          <td class="text-center">{{results[0]}}</td>
          <td class="text-center">{{results[1]}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  


{% endblock %}